
export const ACTIONS = {
    SET_ACCOUNT: 'SET_ACCOUNT',
    SET_NODE_API: 'SET_NODE_API',
    SET_KEYRING_ACCOUNTS: 'SET_KEYRING_ACCOUNTS',
    SET_KEYRING_ACCOUNT: 'SET_KEYRING_ACCOUNT',
    SET_KEYRING_BURN_ACCOUNT: 'SET_KEYRING_BURN_ACCOUNT',
    SET_KEYRING_SOURCE_ACCOUNT: 'SET_KEYRING_SOURCE_ACCOUNT',
    SET_TRACK_INDEX: 'SET_TRACK_INDEX'
};